#!/bin/sh

# gstopdf17 - Ghostscript-based PDF filter for CUPS
#
# (C) 2019 Nelson Lago <lago@ime.usp.br>
# Based on gstopdf from OpenPrinting cups-filters package,
# (C) 2012 Till Kamppeter <till.kamppeter@gmail.com>
#
# Released under GPL 2 or later
#
# gstopdf uses gstoraster which, in turn, uses GhostScript
# with the -dCompatibilityLevel=1.3 option. In this script,
# we directly call GhostScript with the same options as
# gstoraster, except for the -dCompatibilityLevel=1.7 option.

echo "DEBUG: gstopdf17 argv[$#] = $@" >&2
echo "DEBUG: PPD: $PPD" >&2

if [ $# -lt 5 -o $# -gt 6 ]; then
    echo "ERROR: gstopdf17 job-id user title copies options [file]" >&2
    exit 1
fi

# Read from given file.
if [ -n "$6" ]; then
    exec <"$6"
fi

/usr/bin/gs -dQUIET -dPARANOIDSAFER -dNOPAUSE -dBATCH -dNOINTERPOLATE \
            -dNOMEDIAATTRS -dShowAcroForm -sstdout=%stderr -sOutputFile=%stdout \
            -sDEVICE=pdfwrite -dCompatibilityLevel=1.7 \
            -dAutoRotatePages=/None -dAutoFilterColorImages=false -dNOPLATFONTS \
            -dColorImageFilter=/FlateEncode -dPDFSETTINGS=/printer \
            -dColorConversionStrategy=/LeaveColorUnchanged - 2>/dev/null
